config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :devices do
    resources :rents, only: [:new, :create]
    resources :reviews, only: [:new, :create]
    resources :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/my_bookings", to: "rents#my_bookings"
  get "/my_devices", to: "devices#my_devices"

  resources :rents, only: [] do
    member do
      patch "accepted"
      patch "pending"
      patch "refused"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :user
  validates :name, :description, :address, :price, presence: true
  has_many :rents, dependent: :destroy
  has_many_attached :photos
  has_many :reviews, dependent: :destroy
  
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :global_search,
  against: [[:address, 'A' ], [:name, 'B' ], [:description, 'C' ]],
  associated_against: {
    user: [ :first_name, :last_name, :nickname ]
  },
  using: {
    tsearch: { prefix: true }
  }
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :device
  validates :date_begin, :date_end, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :device
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
  validates :content, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :devices, dependent: :destroy
  has_many :rents, dependent: :destroy
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:query].present?
      @devices = Device.global_search(params[:query])
    else
      @devices = Device.all
      @markers = @devices.geocoded.map do |device|
        {
          lat: device.latitude,
          lng: device.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: { device: device })
        }
      end
    end
  end

  def show
    @device = Device.find(params[:id])
    @rent = Rent.new
    @review = Review.new
    @reviews = @device.reviews
    @average_rating = @reviews.average(:rating)
  end

  def new
    @device = Device.new
  end

  def edit
    @device = Device.find(params[:id])
  end

  def create
    @device = Device.new(device_params)
    @device.user = current_user
    if @device.save
      redirect_to my_devices_path
    else
      render :new
    end
  end

  def update
    @device = Device.find(params[:id])
    if @device.update(device_params)
      redirect_to @device
    else
      render :edit
    end
  end

  def destroy
    @device = Device.find(params[:id])
    @device.destroy
    redirect_to my_devices_path
  end

  def my_devices
    @my_devices = Device.where("user_id = ?", current_user)
    @booked_devices = Rent.where(device: @my_devices)
  end

  private

  def device_params
    params.require(:device).permit(:name, :description, :address, :price, :brand, :controller, :game, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def create
    @rent = Rent.new(rent_params)

    @rent.user = current_user
    @rent.device = Device.find(params[:device_id])
    if @rent.save
      redirect_to my_bookings_path
    else
      @device = @rent.device
      render "devices/show"
    end
  end

  def my_bookings
    @my_bookings = Rent.where("user_id = ?", current_user)
  end

  def accepted
    @rent = Rent.find(params[:id])
    @rent.status = "accepted"
    @rent.save
    redirect_to "/my_devices"
  end

  def pending
    @rent = Rent.find(params[:id])
    @rent.status = "pending"
    @rent.save
    redirect_to "/my_devices"
  end

  def refused
    @rent = Rent.find(params[:id])
    @rent.status = "refused"
    @rent.save
    redirect_to "/my_devices"
  end
  
  private

  def rent_params
    params.require(:rent).permit(:date_begin, :date_end, :device_id, :status)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @device = Device.find(params[:device_id])
  end

  def create
    @device = Device.find(params[:device_id])
    @review = Review.new(review_params)
    @review.device = @device
    @rent = Rent.new
    if @review.save
      redirect_to device_path(@device)
    else
      raise
      render 'devices/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/devices/_info_window.html.erb
<h2><%= device.name %></h2>
<p><%= device.address %></p>

app/views/devices/create.html.erb
<h1>Devices#create</h1>
<p>Find me in app/views/devices/create.html.erb</p>

app/views/devices/edit.html.erb
<div class="container-footer">
  <div class="container mt-5">
    <div class="row">
      <div class="col-12 col-sm-8 col-md-4 offset-12 offset-sm-8 offset-md-4">
        <div class="container-new">
        <%= simple_form_for(@device) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :brand %>
          <%= f.input :controller %>
          <%= f.input :game %>
          <%= f.input :address %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <div class="btn-container">
            <div class="formnew">
              <%= f.button :submit, class: 'btn-show' %>
              <% end %>
              <%= link_to 'back to my devices', my_devices_path, class: 'btn-show'%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% console %>

app/views/devices/index.html.erb
<div class="banner">
  <div class="banner-description">
    <h1> Dream big, play more <i class="fas fa-user-astronaut"></i> </h1>
    <p>Rent your favorite console right now !</p>
        <%= form_tag devices_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type an address, a console ..."
          %>
        <%= submit_tag "Search", class: "btn btn-primary btn-sm btn-block" %>
        <% end %>
  </div>
</div>
<div class="map-container">
  <div class="container">
    <div class="cards-list">
      <% @devices.each do |device| %>
        <%= link_to device_path(device) do  %>
          <div class="card-device">
            <div class="card-device-image">
              <% if device.photos.attached? %>
                <%= cl_image_tag device.photos.first.key, height: 200, crop: :fill %>
              <% end %>
            </div>
            <div class="card-device-description">
              <div class="device-brand">
                <div class="device-name"> <h2><%=device.name%></h2></div>
                <div><%=device.controller%> controller(s)</div>
              </div>
              <div class="device-description"> <h5><%=device.description%></h5></div>
              <div class="device-pricing">
                <div class="device-adress"><%= device.address%></div>
                <div class="device-price"><%=device.price%>€ per day</div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div id="map"
       data-markers="<%= @markers.to_json %>"
       data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/devices/my_devices.html.erb
<div class="container-devices">
  <div class="row">
    <div class="container-item col-6">
      <h2>My devices</h2>
      <div data-spy="scroll" data-target="#list-example" data-offset="0" class="scrollspy-example">
        <ul>
          <% @my_devices.each do |device| %>
          <li>
            <div class="card-trip">
            <% if device.photos.attached? %>
              <%= cl_image_tag device.photos.first.key, height: 500, crop: :fill %>
            <% end %>
              <div class="card-trip-infos">
                <div>
                  <h2><%= device.name %></h2>
                  <br>
                  <div class="show-btn">
                    <% if user_signed_in? && device.user_id == current_user.id%>
                    <%= link_to 'edit product', edit_device_path(device)%> | <%= link_to 'destroy', device_path(device), method: :delete %>
                    <% end %>
                  </div>
                </div>
                <h2 class="card-trip-pricing"><%= device.price %>€ per day</h2>
              </div>
            </div>
            <br>
            <br>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <div class="container-item col-6">
      <h2>Booking and validations</h2>
      <% if @booked_devices.empty? %>
        <div class="container-item-1">
          <h2>Sorry, none of your devices are booked ...</h2>
        </div>
      <% else %>
        <ul>
          <% @booked_devices.each do |booking| %>
          <li>
            <div class="card-product">
            <% if booking.device.photos.attached? %>
              <%= cl_image_tag booking.device.photos.first.key, height: 100, crop: :fill %>
            <% end %>
              <div class="card-container">
                <div class="card-product-infos">
                <h2><%= booking.device.name %></h2>
                the total price is: <%= (booking.date_end - booking.date_begin).to_i * booking.device.price %>€
                <br>
                From <%= booking.date_begin %> to <%= booking.date_end %>
                </div>
                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%= booking.status %>
                  </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <ul>
                        <li><%= link_to "accepted", accepted_rent_path(booking), method: :patch %></li>
                        <li><%= link_to "pending", pending_rent_path(booking), method: :patch %></li>
                        <li><%= link_to "refused", refused_rent_path(booking), method: :patch %></li>
                     </ul>
                    </div>
                  </div>
                  <br>
              <% end %>
              </div>
            </div>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/devices/new.html.erb
<div class="container-footer">
  <div class="container mt-5">
    <div class="row">
      <div class="col-12 col-sm-8 col-md-4 offset-12 offset-sm-8 offset-md-4">
        <div class="container-new mb-5">
        <%= simple_form_for(@device, remote: true) do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :brand %>
          <%= f.input :controller %>
          <%= f.input :game %>
          <%= f.input :address %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <div class="btn-container">
            <div class="btn-formnew">
              <%= f.button :submit, class: 'btn-show' %>
              <% end %>
              <%= link_to 'Back to index', devices_path, class: 'btn-show' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/devices/show.html.erb
<div class="container">
  <div class="carousel-name">
    <div class="carousel-description mb-4">
      <%= @device.name %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row mb-4">
    <div class="col-sm-6 mt-3">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
          <% if @device.photos.attached? %>
                <%= cl_image_tag @device.photos.first.key, height: 300, width: 540, crop: :fill %>
              <% end %>
          </div>
          <div class="carousel-item">
            <% if @device.photos.attached? %>
                <%= cl_image_tag @device.photos.first.key, height: 300, width: 540, crop: :fill %>
              <% end %>
          </div>
          <div class="carousel-item">
            <% if @device.photos.attached? %>
                <%= cl_image_tag @device.photos.first.key, height: 300, width: 540, crop: :fill %>
              <% end %>
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="container py-3">
        <div class="row">
          <div class="cardshow col-md-8" style="width: 30rem;">
            <div class="card-header">
              Features
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item"> <strong>Description :</strong> <%= @device.description %></li>
              <li class="list-group-item"> <strong>Brand :</strong> <%= @device.brand %></li>
              <li class="list-group-item"> <strong>Price :</strong> <%= @device.price %>€ per day</li>
              <li class="list-group-item"> <strong>Controllers :</strong> <%= @device.controller %></li>
              <li class="list-group-item"> <strong>Games provided :</strong> <%= @device.game %></li>
              <li class="list-group-item"> <strong>Localisation :</strong> <%= @device.address %></li>
           </ul>
          </div>
          <div class="card-booking col-md-4">
          <%= simple_form_for [@device, @rent] do |f|%>
            <%= f.input :date_begin, as: :string, required: false, input_html: {class: "datepicker"}%>
            <%= f.input :date_end, as: :string, required: false, input_html: {class: "datepicker"} %>
            <div class="d-flex justify-content-between mt-3 col border-top">
              <div class="card-booking-text">
              </div>
            </div>
            <%= f.button :submit,'Send the request', class: 'btn-show mt-5' %>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <% if @device.reviews.blank? %>
    Be the first to leave a review for <%= @device.name %>
  <% else %>
    <h4><strong><%= pluralize @device.reviews.size, "review" %></strong> :</h4>
    <h6>Average rating : <%= @average_rating.round(2) %></h6>
    <div class="reviews">
      <% @reviews.each do |review| %>
      <div class="border border-white m-2 p-2 rounded">
      <h5>Review :</h5>
      <h6><strong><%= review.title %></strong></h6>
        <p>
          <% review.rating.times do %>
            <i class="fas fa-star"></i>
          <% end %>
          <% (5 - review.rating).times do %>
            <i class="far fa-star"></i>
          <% end %>
        </p>
        <div class="content">
        <h6><%= review.content %></h6>
        </div>
        </div>
      <% end %>
  <% end %>
    </div>
</div>

<div class="container border-top">
  <% if user_signed_in? && @device.user_id != current_user.id %>
  <div class="mt-3">
  <h5><strong>Add a review :</strong></h5>
  </div>
    <%= simple_form_for([@device, Review.new], remote: true) do |f| %>
  <%= f.input :title %>
  <%= f.input :rating, input_html: {value: 0}, as: :hidden %>
    <h6>Number of stars :</h6>
    <div class="my-2">
        <% 5.times do |index| %>
          <i id="<%= index + 1 %>" class="review-rating far fa-star"></i>
        <% end %>
    </div>
    <%= f.input :content %>
    <%= f.button :submit, class: "btn btn-primary mb-4" %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shareit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel = "icon" href =  "https://www.flaticon.com/svg/static/icons/svg/316/316319.svg" type = "image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application','data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %> 
  </body>
</html>

app/views/pages/home.html.erb
<div class="pages">
  <div class="banner-description">
    <h1> Play with your friends ! </h1>
    <p>Rent your favorite console right now !</p>
<%=link_to devices_path do  %>
<div class="btn-login">Start here</div>
<% end %>
  </div>
</div>
<div class="container">
  <div class="pages-description">
    <h1> Need ideas of games to play ?</h1>
  </div>
  <div class="cards-list-home">
    <div class="card-device-home">
      <div class="card_image"> <img src="https://geeko.lesoir.be/wp-content/uploads/sites/58/2020/11/BO-Cold-War-Reveal-Tout.jpg" /> </div>
      <div class="card_title title-white">
      </div>
    </div>

      <div class="card-device-home">
      <div class="card_image">
        <img src="https://www.journaldugeek.com/content/uploads/2020/10/amongus-logo.jpg" />
        </div>
      <div class="card_title title-white">
      </div>
    </div>

    <div class="card-device-home">
      <div class="card_image">
        <img src="https://cdn03.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_TheWitcher3WildHuntCompleteEdition_enGB.jpg" />
      </div>
      <div class="card_title">
      </div>
    </div>
</div>
</div>

app/views/rents/my_bookings.html.erb
<div class="container-bookings">
  <h2>My booking</h2>
  <% if @my_bookings.empty? %>
    <div class="container-item-1">
      <h2>You have 0 bookings</h2>
    </div>
  <% else %>
    <h2>You have <%= @my_bookings.count %> bookings</h2>
    <div class="container-card">
      <div class="col-md-12">
        <ul>
          <% @my_bookings.each do |booking| %>
            <li>
              <div class="card-product">
                <% if booking.user_id == current_user.id %>
                <% if booking.device.photos.attached? %>
                <%= cl_image_tag booking.device.photos.first.key, height: 100, crop: :fill %>
                <% end %>
                  <div class="card-container">
                    <div class="card-product-infos">
                      <h2><%= booking.device.name %></h2>
                      the total price is: <%= (booking.date_end - booking.date_begin).to_i * booking.device.price %>€
                      <br>
                      From <%= booking.date_begin %> to <%= booking.date_end %>
                    </div>
                  </div>
                      <div class="card-btn">
                        <% if booking.status == 'accepted' %>
                        <div class="btn btn-success">Accepted</div>
                        <% elsif booking.status == 'refused' %>
                        <div class="btn btn-danger">Refused</div>
                        <% else %>
                        <div class="btn btn-warning"><%= booking.status %></div>
                        <% end %>
                      </div>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/show.html.erb
show.html.erb

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-dark <%= 'd-none' if params[:controller] == 'devise/sessions' %> <%= 'd-none' if params[:controller] == 'pages/home' %> <%= 'd-none' if current_page?(new_device_path) || (params[:controller] == 'devices' && params[:action] == 'create') %> <%= 'fixed-bottom' if params[:controller] == 'rents' && params[:action] == 'my_bookings' %> <%= 'd-none' if params[:controller] == 'rents' && params[:action] == 'my_bookings' %> <%= 'd-none' if params[:controller] == 'devices' && params[:action] == 'my_devices' %> <%= 'd-none' if params[:controller] == 'devices' && params[:action] == 'edit' %> >
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-3 item">
          <h3>Services</h3>
            <ul>
              <li>Web design</li>
              <li>Development</li>
              <li>Trying to code sometimes</li>
            </ul>
        </div>
        <div class="col-sm-6 col-md-3 item">
          <h3>About</h3>
          <ul>
            <li>Wagon</li>
            <li>Kap Track Team</li>
            <li>Learning to dev</li>
          </ul>
        </div>
        <div class="col-md-6 item text">
          <h3>Kap Track Team for Share it Play it</h3>
          <p>Welcome to the new gaming world</p>
        </div>
        <div class="col item social">
          <a href="#"><i class="fab fa-facebook-f"></i></a>
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
        </div>
      </div>
      <p class="copyright">Kap Track © 2020</p>
    </div>
  </footer>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'fixed-top' if params[:controller] == 'devices' || params[:controller] == 'pages' && params[:action] == 'index' || params[:action] == 'home' %> <%= 'colored-navbar' unless current_page?(root_path) || current_page?(devices_path) %> <%= 'sticky-top' unless current_page?(root_path) || current_page?(devices_path) %>">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://cdn1.iconfinder.com/data/icons/youtuber/256/youtube-gaming-logo-512.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "All consoles", devices_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/MaxenceLenoir", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", '#', class: "dropdown-item" %>
            <%= link_to "Add an offer", new_device_path, class: "dropdown-item" %>
            <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "My devices", my_devices_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>